import subprocess

if __name__ == '__main__':
    subprocess.run('apt-get update', shell=True)
    subprocess.run('apt-get install ebtables arptables -y', shell=True)
    subprocess.run('echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf', shell=True)
    subprocess.run('echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf', shell=True)
    subprocess.run('sysctl --system', shell=True)
    subprocess.run('modprobe br_netfilter', shell=True)
    subprocess.run('swapoff -a', shell=True)
    subprocess.run('apt-get update', shell=True)
    subprocess.run('apt install docker.io -y', shell=True)
    subprocess.run('apt-get update', shell=True)
    subprocess.run('curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add', shell=True)
    subprocess.run('apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"', shell=True)
    subprocess.run('apt-get update', shell=True)
    subprocess.run('apt-get install -y kubelet kubeadm kubectl', shell=True)
    subprocess.run('apt-mark hold kubeadm kubelet kubectl', shell=True)
    subprocess.run('hostnamectl set-hostname master01', shell=True)
    subprocess.run('kubeadm init --pod-network-cidr=192.168.0.0/16', shell=True)
    subprocess.run('mkdir -p $HOME/.kube', shell=True)
    subprocess.run('cp -i /etc/kubernetes/admin.conf $HOME/.kube/config', shell=True)
    subprocess.run('chown $(id -u):$(id -g) $HOME/.kube/config', shell=True)
    #subprocess.run('curl https://docs.projectcalico.org/manifests/calico.yaml -O', shell=True)
    subprocess.run('kubectl apply -f calico.yaml', shell=True)
    subprocess.run('kubectl taint nodes --all node-role.kubernetes.io/master-', shell=True)
    subprocess.run('kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=ens.*', shell=True)