apiVersion: v1
kind: Service
metadata:
  name: my-python-service
spec:
  selector:
    app: my-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python
spec:
  selector:
    matchLabels:
      app: my-python
  replicas: 1
  template:
    metadata:
      labels:
        app: my-python
    spec:
      containers:
      - name: my-python
        image: mypythonapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
